#!/bin/bash

# example of configure command
# run on tmp-XXX dir

LIBXC_version=`egrep "^name = libxc-[0-9].*$" ../config/specs/fallbacks.conf | cut -d'-' -f2`
NetCDF_version=`egrep "^name = netcdf-[0-9].*$" ../config/specs/fallbacks.conf | cut -d'-' -f2`
NetCDFF_version=`egrep "^name = netcdf-fortran-[0-9].*$" ../config/specs/fallbacks.conf | cut -d'-' -f3`

../configure \
--prefix=${FALLBACKS_PATH} \
--with-linalg-libs="-L/usr/lib64 -lopenblas" \
--with-yaml-incs="-I/usr/include" \
--with-yaml-libs="-L/usr/lib64 -lyaml" \
--disable-atompaw --disable-wannier90 --disable-xmlf90 --disable-libpsml \
--with-libxc-libs="-L${FALLBACKS_PATH}/libxc/${LIBXC_version}/lib -lxcf90 -lxc" \
--with-libxc-incs="-I${FALLBACKS_PATH}/libxc/${LIBXC_version}/include "



#--with-netcdf4-libs="-L${FALLBACKS_PATH}/netcdf4/${NetCDF_version}/lib -lnetcdf" \
#--with-netcdf4-incs="-I${FALLBACKS_PATH}/netcdf4/${NetCDF_version}/include " \
#--with-netcdf4-bins="${FALLBACKS_PATH}/netcdf4/${NetCDF_version}/bin " \
#--with-netcdf4-fortran-libs="-L${FALLBACKS_PATH}/netcdf4_fortran/${NetCDFF_version}/lib -lnetcdff" \
#--with-netcdf4-fortran-incs="-I${FALLBACKS_PATH}/netcdf4_fortran/${NetCDFF_version}/include " \

#--disable-libxc
#--disable-netcdf4 --disable-netcdf4-fortran
#--disable-bigdft 
#--disable-yaml
